# Generated by Django 4.1.3 on 2023-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
