# Generated by Django 4.1.3 on 2023-04-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_product_report_promp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='promp',
        ),
    ]
