# Generated by Django 4.1.3 on 2023-04-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_report_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='product',
            new_name='promp',
        ),
    ]
